play.http.secret.key="${CORTEX_PLAY_SECRET}"

env {
  os_auth_url = "http://192.168.1.254:5000/v3"
  os_project  = "ZTA-SIEM-SOAR"
  aws_region  = "${AWS_REGION}"
  thehive_api_key = "${THEHIVE_API_KEY}"
  aws_access_key_id = "${AWS_ACCESS_KEY_ID}"
  aws_secret_access_key = "${AWS_SECRET_ACCESS_KEY}"
}

# TODO: populate from IMPLEMENTATION.md §11.2 and §11.3
