agent {
	data_dir      = "/run/spire"
	log_level     = "INFO"
	trust_domain  = "ztlab.local"
	server_address = "10.10.3.10"
	server_port   = "8081"
	socket_path   = "/run/spire/sockets/agent.sock"

	join_token = "${JOIN_TOKEN}"
}

plugins {
	NodeAttestor "k8s_psat" {
		plugin_data {
			cluster = "aws-k3s"
		}
	}

	KeyManager "memory" { plugin_data {} }

	WorkloadAttestor "k8s" {
		plugin_data {
			skip_kubelet_verification = true
		}
	}
}
