all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/ztlab-key
    ansible_host_key_checking: false

  children:
    ssh_entrypoints:
      hosts:
        aws_bastion:
          ansible_host: 52.221.255.36
        aws_gateway:
          ansible_host: 13.213.245.227
          wg_tunnel_ip: "10.200.0.1"
          wg_peer_routes: "192.168.100.0/24,192.168.101.0/24,192.168.102.0/24"

    aws_private:
      vars:
        ansible_ssh_common_args: >-
          -o ProxyJump=ubuntu@52.221.255.36
          -o StrictHostKeyChecking=no
      hosts:
        aws_k3s_master:   { ansible_host: 10.10.1.10 }
        aws_k3s_worker_1: { ansible_host: 10.10.1.11 }
        aws_security:     { ansible_host: 10.10.1.20 }

    aws_monitoring:
      vars:
        ansible_ssh_common_args: >-
          -o ProxyJump=ubuntu@52.221.255.36
          -o StrictHostKeyChecking=no
      hosts:
        aws_loki: { ansible_host: 10.10.2.10 }

    openstack:
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        cloud_provider: "openstack"    # dùng trong promtail-config.yml.j2
      children:
        os_dmz:
          hosts:
            os_gateway:
              ansible_host: 10.10.10.188    # OpenStack floating IP
              wg_tunnel_ip: "10.200.0.2"
              wg_peer_routes: "10.10.1.0/24,10.10.2.0/24,10.10.4.0/24"
        os_private:
          vars:
            ansible_ssh_common_args: >-
              -o ProxyJump=ubuntu@52.221.255.36
              -o StrictHostKeyChecking=no
          hosts:
            os_k3s_master: { ansible_host: 10.10.1.12 }  # worker-2 repurposed

    aws:
      vars:
        cloud_provider: "aws"    # dùng trong promtail-config.yml.j2
      children:
        ssh_entrypoints:
        aws_private:
        aws_restricted:
