all:
  vars:
    ansible_user: ubuntu
    ansible_port: 22
    ansible_python_interpreter: /usr/bin/python3
  children:
    ssh_entrypoints:
      hosts:
        aws_gateway:
        aws_bastion:
        os_gateway:
    aws_private:
      hosts:
        aws_k3s_master:
        aws_k3s_worker_1:
        aws_k3s_worker_2:
        aws_security:
        aws_siem:
    aws:
      hosts:
        aws_gateway:
          ansible_host: 54.251.163.70
        aws_bastion:
          ansible_host: 47.128.255.237
        aws_k3s_master:
          ansible_host: 10.10.1.10
          ansible_ssh_common_args: '-o ProxyJump=ubuntu@47.128.255.237 -o StrictHostKeyChecking=no -o ConnectTimeout=15'
        aws_k3s_worker_1:
          ansible_host: 10.10.1.11
          ansible_ssh_common_args: '-o ProxyJump=ubuntu@47.128.255.237 -o StrictHostKeyChecking=no -o ConnectTimeout=15'
        aws_k3s_worker_2:
          ansible_host: 10.10.1.12
          ansible_ssh_common_args: '-o ProxyJump=ubuntu@47.128.255.237 -o StrictHostKeyChecking=no -o ConnectTimeout=15'
        aws_security:
          ansible_host: 10.10.1.20
          ansible_ssh_common_args: '-o ProxyJump=ubuntu@47.128.255.237 -o StrictHostKeyChecking=no -o ConnectTimeout=15'
        aws_siem:
          ansible_host: 10.10.2.10
          ansible_ssh_common_args: '-o ProxyJump=ubuntu@47.128.255.237  -o StrictHostKeyChecking=no -o ConnectTimeout=15'
    openstack:
      vars:
        ansible_ssh_private_key_file: ~/.ssh/zta-siem-soar-key
        os_gateway_floating_ip: 172.10.10.168
        ansible_ssh_common_args: '-o ProxyCommand="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -W %h:%p ubuntu@{{ os_gateway_floating_ip }}" -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ConnectTimeout=15'
      hosts:
        os_gateway:
          ansible_host: 172.10.10.168
          ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ConnectTimeout=15'
        os_k3s_master:
          ansible_host: 192.168.101.11
        os_k3s_worker_1:
          ansible_host: 192.168.101.12
        os_k3s_worker_2:
          ansible_host: 192.168.101.13
        os_identity:
          ansible_host: 192.168.102.10
