all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/zta-siem-soar-key
    ansible_host_key_checking: false

  children:
    ssh_entrypoints:
      hosts:
        aws_bastion:
          ansible_host: 54.169.37.66
        aws_gateway:
          ansible_host: 13.213.245.227

    aws_private:
      vars:
        ansible_ssh_common_args: >-
          -o ProxyJump=ubuntu@54.254.252.106
          -o StrictHostKeyChecking=no
      hosts:
        aws_k3s_master:   { ansible_host: 10.10.1.10 }
        aws_k3s_worker_1: { ansible_host: 10.10.1.11 }
        aws_security:     { ansible_host: 10.10.1.20 }

    aws_restricted:
      vars:
        ansible_ssh_common_args: >-
          -o ProxyJump=ubuntu@54.254.252.106
          -o StrictHostKeyChecking=no
      hosts:
        aws_siem: { ansible_host: 10.10.2.10 }

    openstack:
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        cloud_provider: "openstack"    # dùng trong promtail-config.yml.j2
      children:
        os_dmz:
          hosts:
            os_gateway:
              ansible_host: 54.254.252.106   # AWS bastion làm jump host cho OS cluster
        os_private:
          vars:
            ansible_ssh_common_args: >-
              -o ProxyJump=ubuntu@54.254.252.106
              -o StrictHostKeyChecking=no
          hosts:
            os_k3s_master: { ansible_host: 10.10.1.12 }  # worker-2 repurposed

    aws:
      vars:
        cloud_provider: "aws"    # dùng trong promtail-config.yml.j2
      children:
        ssh_entrypoints:
        aws_private:
        aws_restricted:
