apiVersion: 1

groups:
  - orgId: 1
    name: ai-analyzer
    folder: ZTLab
    interval: 1m
    rules:
      - uid: ai-malicious-log-alert
        title: AI Malicious Log Detected
        for: 0s
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: Loki
            model:
              expr: '{job="ai-analyzer"} |= "ai_security_alert"'
