apiVersion: 1

groups:
  - orgId: 1
    name: soar-engine
    folder: ZTLab
    interval: 1m
    rules:
      - uid: soar-action-log-alert
        title: SOAR Action Recorded
        for: 0s
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: Loki
            model:
              expr: '{job="soar-engine"} |= "soar_action"'
