server {
	bind_address = "0.0.0.0"
	bind_port    = "8081"
	trust_domain = "ztlab.local"
	data_dir     = "/opt/spire/data/server"
	log_level    = "INFO"

	ca_subject {
		country      = ["VN"]
		organization = ["ZT-Lab"]
		common_name  = ""
	}

	default_x509_svid_ttl = "1h"
	default_jwt_svid_ttl  = "5m"
	ca_ttl                = "168h"
}

plugins {
	DataStore "sql" {
		plugin_data {
			database_type = "sqlite3"
			connection_string = "/opt/spire/data/server/datastore.sqlite3"
		}
	}

	KeyManager "disk" {
		plugin_data {
			keys_path = "/opt/spire/data/server/keys.json"
		}
	}

	NodeAttestor "k8s_psat" {
		plugin_data {
			clusters = {
				"aws-k3s" = {
					service_account_allow_list = ["spire:spire-agent"]
					kube_config_file = "/root/.kube/aws-config"
				}
				"os-k3s" = {
					service_account_allow_list = ["spire:spire-agent"]
					kube_config_file = "/root/.kube/os-config"
				}
			}
		}
	}
}
