[Interface]
Address = 10.10.0.2/24
PrivateKey = ${WG_PRIVATE_KEY}

PostUp   = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
PublicKey = ${AWS_GATEWAY_PUBLIC_KEY}
Endpoint = ${AWS_EIP}:51820
AllowedIPs = 10.10.0.0/24, 10.10.1.0/24, 10.10.2.0/24, 10.10.3.0/24, 10.42.0.0/16, 10.43.0.0/16
PersistentKeepalive = 25
